server:
  port: 8080
spring:
  mail:
    host: smtp.126.com
    username: ********
    password: ********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
